name: ancap-simulation

services:
  ancap-bot:
    build:
      context: .
    container_name: ancap_simulation_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    command: python bot.py
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - default
      - debug

  db:
    image: postgres:15
    container_name: ancap_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_name
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - default

volumes:
  db_data:

